name: Vyhledat a nainstalovat Windows Updates
  hosts: all
  tasks:
    - name: Instalace kritickych a bezpecnostnich aktualizaci
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        reboot: yes
        reboot_timeout: 1200
